client
ArtMaxDev/lab pull request #28
Opened 2018-09-21 18:10 UTC by ODDsama

2018-09-21 18:56 UTC, artemsky requested changes

2018-09-21 18:56 UTC, artemsky commented on package.json
> +    "laravel-mix": "^2.1.14",
?

2018-09-21 18:56 UTC, artemsky commented on package.json
> +    "browser-sync": "^2.24.7",
?

2018-09-21 18:56 UTC, artemsky commented on resources/views/client/components/news-item.blade.php
> +        <img src="{{$news->image}}0" alt="" class="img" width="100%" height="230px">
0?)

2018-09-21 18:56 UTC, artemsky commented on resources/views/client/pages/index.blade.php
> +    @if($news->count())
А это зачем?

2018-09-22 12:57 UTC, ODDsama commented on resources/views/client/pages/index.blade.php
> +    @if($news->count())
чтобы блок новостей не выводился пока нет новостей

2018-09-22 13:30 UTC, artemsky approved these changes

2018-09-22 14:39 UTC, merged